name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - dask
  - cartopy
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake::intake-xarray
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - numba
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipyvolume
  - widgetsnbextension
  - nodejs
  - ipywidgets
  - graphviz
  - nodejs
  - pyresample
  - xgcm
  - xmitgcm
  - cmocean
  - holoviews
  - pip:
    - kubernetes
    - graphviz
